apiVersion: v1
kind: Service
metadata:
    name: hackathonchatgptnttdataeurekaserver
spec:
    type: LoadBalancer
    ports:
    - port: 8761 
    selector:
        app: hackathonchatgptnttdataeurekaserver